name: gendiff-check
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Собираем проект
        run: make setup
      - name: Запускаем линтер
        run: make lint
      - name: Запускаем тесты
        run: make test
      - name: Тестирование и публикование покрытия тестами на Codeclimate
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
